// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using jualapi;

namespace jualapi.Migrations
{
    [DbContext(typeof(jualoverflowContext))]
    partial class jualoverflowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("jualapi.Models.Answers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("QuestionsId");

                    b.Property<int>("Votes");

                    b.HasKey("Id");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("jualapi.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.Property<int>("Votes");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new { Id = -1, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 0 },
                        new { Id = -2, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 10 },
                        new { Id = -3, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 110 },
                        new { Id = -4, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 10 },
                        new { Id = -5, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 11 },
                        new { Id = -6, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 9 },
                        new { Id = -7, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 10 },
                        new { Id = -8, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 0 },
                        new { Id = -9, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 0 },
                        new { Id = -10, Content = "Code works with pure and simple magic, there is no rhyme or reason, it is literally generated from thin air", Title = "How does code work?", Votes = 0 }
                    );
                });

            modelBuilder.Entity("jualapi.Models.Answers", b =>
                {
                    b.HasOne("jualapi.Models.Questions", "Questions")
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
